/* DO NOT EDIT THIS FILE - it is machine generated */
/* Generated for class grame.sound.audioengine.AudioStreamFactory */
/* Generated from AudioStreamFactory.java*/

#ifndef _Included_grame_sound_audioengine_AudioStreamFactory
#define _Included_grame_sound_audioengine_AudioStreamFactory
#include <jni.h>
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    Init
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_grame_sound_audioengine_AudioStreamFactory_Init
    (JNIEnv *, jclass);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    Destroy
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_grame_sound_audioengine_AudioStreamFactory_Destroy
    (JNIEnv *, jclass);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeNullSound
     * Signature: (I)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeNullSound
    (JNIEnv *, jclass, jint);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeReadSound
     * Signature: (Ljava/lang/String;)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeReadSound
    (JNIEnv *, jclass, jstring);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeWriteSound
     * Signature: (Ljava/lang/String;I)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeWriteSound
    (JNIEnv *, jclass, jstring, jint);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeRegionSound
     * Signature: (Ljava/lang/String;II)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeRegionSound
    (JNIEnv *, jclass, jstring, jint, jint);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeLoopSound
     * Signature: (II)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeLoopSound
    (JNIEnv *, jclass, jint, jint);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeFadeSound
     * Signature: (III)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeFadeSound
    (JNIEnv *, jclass, jint, jint, jint);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeCutSound
     * Signature: (III)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeCutSound
    (JNIEnv *, jclass, jint, jint, jint);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeSeqSound
     * Signature: (II)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeSeqSound
    (JNIEnv *, jclass, jint, jint);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeMixSound
     * Signature: (II)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeMixSound
    (JNIEnv *, jclass, jint, jint);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeTransformSound
     * Signature: (IIII)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeTransformSound
    (JNIEnv *, jclass, jint, jint, jint, jint);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeConvertSound
     * Signature: (IID)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeConvertSound
    (JNIEnv *, jclass, jint, jint, jdouble);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeInputSound
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeInputSound
    (JNIEnv *, jclass);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    MakeNativeSound
     * Signature: (Lgrame/sound/audioengine/TAudioStream;)I
     */
    JNIEXPORT jint JNICALL Java_grame_sound_audioengine_AudioStreamFactory_MakeNativeSound
    (JNIEnv *, jclass, jobject);

    /*
     * Class:     grame_sound_audioengine_AudioStreamFactory
     * Method:    DeleteSound
     * Signature: (I)I
     */
    JNIEXPORT void JNICALL Java_grame_sound_audioengine_AudioStreamFactory_DeleteSound
    (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
