# Find librubberband

FIND_PATH(RUBBERBAND_INCLUDE_DIR rubberband-c.h)

SET(RUBBERBAND_NAMES ${RUBBERBAND_NAMES} rubberband librubberband)
FIND_LIBRARY(RUBBERBAND_LIBRARY NAMES ${RUBBERBAND_NAMES} PATH)

IF(RUBBERBAND_INCLUDE_DIR AND RUBBERBAND_LIBRARY)
	SET(RUBBERBAND_FOUND TRUE)
ENDIF(RUBBERBAND_INCLUDE_DIR AND RUBBERBAND_LIBRARY)

IF(RUBBERBAND_FOUND)
	IF(NOT RUBBERBAND_FIND_QUIETLY)
		MESSAGE(STATUS "Found RUBBERBAND: ${RUBBERBAND_LIBRARY}")
	ENDIF (NOT RUBBERBAND_FIND_QUIETLY)
ELSE(RUBBERBAND_FOUND)
	IF(RUBBERBAND_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find RUBBERBAND")
	ENDIF(RUBBERBAND_FIND_REQUIRED)
ENDIF (RUBBERBAND_FOUND)
